[package]
name = "calx-resource"
version = "0.3.0-alpha"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Smart pointer for static resources"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
rustc-serialize = "0.3"
