[package]

name = "magog"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[[bin]]

name = "magog"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
