[package]

name = "magog"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[[bin]]

name = "magog"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"
