[package]
name = "calx-ecs"
version = "0.3.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Serializable entity component system for games"
keywords = ["gamedev", "ecs"]
repository = "https://github.com/rsaarelm/calx-ecs"
license = "MIT OR Apache-2.0"

[dependencies]
fnv = "1.0"
rustc-serialize = "0.3"

[dev-dependencies]
bincode = "0.6"
