[package]

name = "magog"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[[bin]]

name = "magog"

[dependencies.image]
git = "https://github.com/PistonDevelopers/rust-image"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"
