[package]

name = "calx"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]
build = "./.build.sh"

[[bin]]

name = "calx"

[dependencies.cgmath-rs]
git = "https://github.com/bjz/cgmath-rs.git"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs.git"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.hgl]
git = "https://github.com/cmr/hgl-rs.git"
