[package]

name = "calx"
version = "0.0.0"
authors = [ "rsaarelm <risto.saarelma@iki.fi>" ]

[lib]
name = "calx"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.image]
git = "https://github.com/PistonDevelopers/rust-image"

[[example]]
name = "demo"
path = "examples/demo/main.rs"
