[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"
build = "build.rs"

[[bin]]
name = "magog"

[profile.release]
lto = true

[dependencies.image]

[dependencies.time]

[dependencies.rustc-serialize]

[dependencies.calx_util]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx_backend]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"
