[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[[bin]]
name = "magog"

[profile.release]
lto = true

[dependencies.num]

[dependencies.rand]

[dependencies.getopts]

[dependencies.toml]

[dependencies.image]

[dependencies.time]

[dependencies.rustc-serialize]

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"

[dependencies.mapgen]
path = "mapgen"
