[package]
name = "calx"
version = "0.0.1"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Rust game development helper library collection"
keywords = ["gamedev"]
license = "MIT"

[[example]]
name = "demo"
path = "examples/demo.rs"

[[example]]
name = "grid"
path = "examples/grid.rs"

[[example]]
name = "isoworld"
path = "examples/isoworld.rs"

[dependencies.rand]

[dependencies.rustc-serialize]

[dependencies.time]

[dependencies.rand_macros]

[dependencies.num]

[dependencies.image]

[dependencies.nalgebra]

[dependencies.glutin]

[dependencies.glium]
