[package]

name = "calx"
version = "0.0.0"
authors = [ "rsaarelm <risto.saarelma@iki.fi>" ]

[lib]
name = "calx"

[dependencies.time]

[dependencies]
rustc-serialize = "0.1.1"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[[example]]
name = "demo"
path = "examples/demo/main.rs"
