[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"
build = "build.rs"

[[bin]]
name = "magog"

[profile.release]
lto = true

[dependencies.bst]
git = "https://github.com/rsaarelm/bst"
#git = "https://github.com/contain-rs/bst"
# TODO: Go back to crates.io version once it's up to current Rust

[dependencies.num]

[dependencies.rand]

[dependencies.rand_macros]

[dependencies.getopts]

[dependencies.image]

[dependencies.time]

[dependencies.rustc-serialize]

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
