[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[workspace]
members = ["world", "display"]

[dependencies]
rand = "0.3"
euclid = "0.15"
time = "0.1"
glium = "0.18"
scancode = "0.1"
serde = "1.0"
calx-ecs = "0.6"
vitral = { git = "https://github.com/rsaarelm/vitral", features = ["glium_backend"] }
calx = { git = "https://github.com/rsaarelm/calx" }
world = { path = "world" }
display = { path = "display" }

[dev-dependencies]
image = "0.17"
structopt = "0.1"
structopt-derive = "0.1"
