[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[[bin]]
name = "magog"

[profile.release]
lto = true

[dependencies]
num = "*"
rand = "*"
getopts = "*"
toml = "*"
image = "*"
time = "*"
rustc-serialize = "*"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx_ecs]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"

[dependencies.content]
path = "content"

[dependencies.render]
path = "render"
