[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[workspace]
members = ["world", "display"]

[dependencies]
calx = { git = "https://github.com/rsaarelm/calx" }
calx-ecs = "0.6"
display = { path = "display" }
env_logger = "0.5"
euclid = "0.19"
glium = "0.22"
rand = { version = "0.5", features = ["serde1"] }
scancode = "0.1"
serde = "1.0"
time = "0.1"
vitral = { git = "https://github.com/rsaarelm/vitral", features = ["glium_backend"] }
world = { path = "world" }

[dev-dependencies]
image = "0.19"
structopt = "0.2"
structopt-derive = "0.2"
