[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[workspace]
members = ["world", "content", "display"]

[profile.release]
lto = true

[dependencies]
rand = "0.3"
euclid = "0.10"
serde = "0.8"
time = "0.1"
glium = "0.15"
scancode = "0.1"

# TODO: Make Vitral into a proper crate eventually.
[dependencies.vitral]
git = "https://github.com/rsaarelm/vitral"

[dependencies.calx-color]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-resource]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-grid]
git = "https://github.com/rsaarelm/calx"

[dependencies.content]
path = "content"

[dependencies.world]
path = "world"

[dependencies.display]
path = "display"
