[package]
name = "calx"
version = "0.0.1"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Rust game development helper library collection"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies.calx_ecs]
path = "calx_ecs"

[dependencies]
rand = "*"
serde = "*"
serde_macros = "*"
bincode = "*"
time = "*"
num = "*"
vec_map = "*"
image = "*"
nalgebra = "*"
glium = "*"
cpal = "*"

[[example]]
name = "demo"
path = "examples/demo.rs"

[[example]]
name = "noise"
path = "examples/noise.rs"

[[example]]
name = "grid"
path = "examples/grid.rs"

[[example]]
name = "isoworld"
path = "examples/isoworld.rs"

[[example]]
name = "window"
path = "examples/window.rs"
