[package]
name = "debris"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Shooter game"
keywords = ["gamedev"]
license = "GPL3"

[[bin]]
name = "debris"

[profile.release]
lto = true

[dependencies]
euclid = "0.7"
image = "0.10"
time = "0.1"
glium = "0.14"
serde = "0.7"

# TODO: Make Vitral into a proper crate eventually.
[dependencies.vitral]
git = "https://github.com/rsaarelm/vitral"

[dependencies.calx-color]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-resource]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "world"
