[package]
name = "calx"
version = "0.0.1"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Rust game development helper library collection"
keywords = ["gamedev"]
license = "MIT"

[dependencies.calx_macros]
path = "calx_macros"

[dependencies.calx_ecs]
path = "calx_ecs"

[dependencies.rand]

[dependencies.rustc-serialize]

[dependencies.time]

[dependencies.num]

[dependencies.vec_map]

[dependencies.image]

[dependencies.nalgebra]

[dependencies.glutin]

[dependencies.glium]

[dependencies.cpal]

[[example]]
name = "demo"
path = "examples/demo.rs"

[[example]]
name = "noise"
path = "examples/noise.rs"

[[example]]
name = "grid"
path = "examples/grid.rs"

[[example]]
name = "isoworld"
path = "examples/isoworld.rs"
