[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"

[workspace]
members = ["world", "display"]

[profile.release]
lto = true

[dependencies]
rand = "0.3"
euclid = "0.11"
time = "0.1"
glium = "0.16"
scancode = "0.1"
serde = "0.9"
calx-ecs = "0.5"
vitral = { git = "https://github.com/rsaarelm/vitral" }
calx-color = { git = "https://github.com/rsaarelm/calx" }
calx-grid = { git = "https://github.com/rsaarelm/calx" }
calx-alg = { git = "https://github.com/rsaarelm/calx" }
world = { path = "world" }
display = { path = "display" }
