[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"
build = "build.rs"

[[bin]]
name = "magog"

[profile.release]
lto = true

[dependencies.collect]
git = "https://github.com/gankro/collect-rs"
# TODO: Go back to crates.io version

[dependencies.num]

[dependencies.rand]

[dependencies.rand_macros]

[dependencies.image]

[dependencies.time]

[dependencies.rustc-serialize]

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
