[package]
name = "calx-ecs"
version = "0.4.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Serializable entity component system for games"
keywords = ["gamedev", "ecs"]
repository = "https://github.com/rsaarelm/calx-ecs"
license = "MIT OR Apache-2.0"

[dependencies]
serde_derive = "0.9"
serde = "0.9"

[dev-dependencies]
serde_json = "0.9"
