map = '''
                                                           * *
                                                        * * * *
                                                     # # # # # #
                                                  * # . . . . . .
                                               * * # . . . . . . .
                                            * * * # . . . . . . . .
                                         * # # # # # # | | # | # # #
                                      * * * * * . . . . . # . . . . .
                                   * * * * * . . . . . * # . . . . . .
                                * * * * * # # . # # * * * * * . . * * *
                             ~ ~ * * * * # . . . # * * * * * . . . * * *
                          , , ~ ~ . * . . . . . . . . . . * * . . * * * *
                       ~ , C , ~ ~ . . # . . . # * * * . * * . . * * * * *
                    ~ ~ , , , ~ ~ . . # # # # # * * * . * * . . * * # # # #
                 . . ~ ~ ~ , ~ ~ * * . . . * * # # # . # # * . . * # . . . #
              * * . . ~ ~ ~ ~ ~ ~ ~ * * . * * # . . . . # * . . * # . . . # *
           * . . * . . . . . . . ~ * . . . * # . . . . # * # | # # # | # # # #
        * * . . . . . . . # # # # ~ ~ ~ . * # . . . . # * # . . . . . . . . # *
     * * * * . . # # # # # . . # . * ~ . ~ * * ~ ~ ~ ~ * # # # # # | # # . # * *
  * * * * A * * . . . . . . . . * * . . . ~ ~ ~ . . . ~ * * * # . . . # . # * * *
 * * * A . . . * # # # # # # # . * * * * . . . . . ~ ~ ~ * * # . . . # | * * * * *
* * * . . A . . * * * * * * * . . . . * * * * * * . . ~ ~ ~ # # # # # . . . . * * *
 * * . * . . A . . . . . * * . . . . . . * * * * * * . . ~ ~ * * * * * . . . = = * *
  * . . . . . . . . * * . * * . * * * . . * * * # # # # . . ~ * * . . . . . = = = *
   * A . * . . * * * * . * * * . . * * * . * * # . . . . ~ ~ * = = . * . . . * * *
    * . * * . * * * * . A * * * . * * * * . . . . . . . ~ * * * = . . * * . * *
     * . . * . * * . . . A * * * . . * . * * # . . . ~ ~ . . * . . = * * * *
      * * . * . * * . A A . . * * . * . . * # . . . ~ ~ . . . . = = = * *
       * * . . . * * . . . . * * . * . . * # # | # ~ ~ . . . . = = = *
        * * . * . . * * . . . . . . * * . . . . * * ~ * . . . = * *
         * * * * . . , * * * * . . . * * * * * * ~ ~ * . . * * *
          * * * * , , , * * . . . . * * * ~ ~ ~ ~ * * . . * *
           C C , , , , , * * . . . * * ~ ~ * ~ * * . . * *
            C , C , , , D * * * . * ~ ~ * * * * . . . *
             , , , D , , , * C * * ~ ~ * . . . . . *
              C , , , , C * C , C * ~ * . . . = =
               , , , , , , B , C ~ ~ * > . = =
                ~ ~ ~ , , B ~ ~ ~ ~ C * * =
                 ~ ~ ~ . ~ ~ ~ ~ C C C C
                  ~ C B ~ ~ , , , C C
                   C C , , , , , C
                    C , E , , ,
                     , , , ,
                      , ,
'''

[legend]
"#" = { t = "Wall", e = [] }
"*" = { t = "Rock", e = [] }
"," = { t = "Grass", e = [] }
"." = { t = "Ground", e = [] }
"=" = { t = "Magma", e = [] }
">" = { t = "Gate", e = [] }
"A" = { t = "Ground", e = ["dreg"] }
"B" = { t = "Grass", e = ["sword"] }
"C" = { t = "Tree", e = [] }
"D" = { t = "Grass", e = ["snake"] }
"E" = { t = "Grass", e = ["player"] }
"|" = { t = "Door", e = [] }
"~" = { t = "Water", e = [] }
