map = '''
                                                           * *
                                                        * * * *
                                                     # # # # # #
                                                  * # . . . . . .
                                               * * # . . . . . . .
                                            * * * # . . . . . . . .
                                         * # # # # # # + + # + # # #
                                      * * * * * . . . . . # . . . . .
                                   * * * * * . . . . . * # . . . . . .
                                * * * * * # # . # # * * * * * . . * * *
                             ~ ~ * * * * # . . . # * * * * * . . . * * *
                          , , ~ ~ . * . . . . . . . . . . * * . . * * * *
                       ~ , % , ~ ~ . . # . . . # * * * . * * . . * * * * *
                    ~ ~ , , , ~ ~ . . # # # # # * * * . * * . . * * # # # #
                 . . ~ ~ ~ , ~ ~ * * . . . * * # # # . # # * . . * # . . . #
              * * . . ~ ~ ~ ~ ~ ~ ~ * * . * * # . . . . # * . . * # . . . # *
           * . . * . . . . . . . ~ * . . . * # . . . . # * # + # # # + # # # #
        * * . . . . . . . # # # # ~ ~ ~ . * # . . . . # * # . . . . . . . . # *
     * * * * . . # # # # # . . # . * ~ . ~ * * ~ ~ ~ ~ * # # # # # + # # . # * *
  * * * * . * * . . . . . . . . * * . . . ~ ~ ~ . . . ~ * * * # . . . # . # * * *
 * * * . . . . * # # # # # # # . * * * * . . . . . ~ ~ ~ * * # . . . # + * * * * *
* * * . . . . . * * * * * * * . . . . * * * * * * . . ~ ~ ~ # # # # # . . . . * * *
 * * . * . . . . . . . . * * . . . . . . * * * * * * . . ~ ~ * * * * * . . . . * * *
  * . . . . . . . . * * . * * . * * * . . * * * # # # # . . ~ * * . . . . . . * * *
   * . . * . . * * * * . * * * . . * * * . * * # . . . . ~ ~ * * * . * . . . * * *
    * . * * . * * * * . . * * * . * * * * . . . . . . . ~ * * * * . . * * . * *
     * . . * . * * . . . . * * * . . * . * * # . . . ~ ~ . . * . . . * * * *
      * * . * * * * . . . . . * * . * . . * # . . . ~ ~ . . . . * * * * *
       * * . . . * * . . . . * * . * . . * # # + # ~ ~ . . . . * * * *
        * * . * . . * * . . . . . . * * . . . . * * ~ * . . . * * *
         * * * * . . , * * * * . . . * * * * * * ~ ~ * . . * * *
          * * * * , , , * * . . . . * * * ~ ~ ~ ~ * * . . * *
           % % , , , , , * * . . . * * ~ ~ * ~ * * . . * *
            % , % , , , , * * * . * ~ ~ * * * * . . . *
             , , , , , , , * % * * ~ ~ * . . . . . *
              % , , , , % * % , % * ~ * . . . . *
               , , , , , , , , % ~ ~ * ^ . * *
                ~ ~ ~ , , , ~ ~ ~ ~ % * * *
                 ~ ~ ~ . ~ ~ ~ ~ % % % %
                  ~ % , ~ ~ , , , % %
                   % % , , , , , %
                    % , , , , ,
                     , , , ,
                      , ,
'''

[legend]
"." = { t = "Ground", e = [] }
"^" = { t = "Gate", e = [] }
"*" = { t = "Rock", e = [] }
"#" = { t = "Wall", e = [] }
"+" = { t = "Door", e = [] }
"~" = { t = "Water", e = [] }
"," = { t = "Grass", e = [] }
"%" = { t = "Tree", e = [] }
