map = '''
                                                           * *
                                                        * * * *
                                                     # # # # # #
                                                  * # . . . . . .
                                               * * # . . . . . . .
                                            * * * # . . . . . . . .
                                         * # # # # # # | | # | # # #
                                      * * * * * . . . . . # . . . . .
                                   * * * * * . . . . . * # . . . . . .
                                * * * * * # # . # # * * * * * . . * * *
                             ~ ~ * * * * # . . . # * * * * * . . . * * *
                          , , ~ ~ . * . . . . . . . . . . * * . . * * * *
                       ~ , A , ~ ~ . . # . . . # * * * . * * . . * * * * *
                    ~ ~ , , , ~ ~ . . # # # # # * * * . * * . . * * # # # #
                 . . ~ ~ ~ , ~ ~ * * . . . * * # # # . # # * . . * # . . . #
              * * . . ~ ~ ~ ~ ~ ~ ~ * * . * * # . . . . # * . . * # . . . # *
           * . . * . . . . . . . ~ * . . . * # . . . . # * # | # # # | # # # #
        * * . . . . . . . # # # # ~ ~ ~ . * # . . . . # * # . . . . . . . . # *
     * * * * . . # # # # # . . # . * ~ . ~ * * ~ ~ ~ ~ * # # # # # | # # . # * *
  * * * * . * * . . . . . . . . * * . . . ~ ~ ~ . . . ~ * * * # . . . # . # * * *
 * * * . . . . * # # # # # # # . * * * * . . . . . ~ ~ ~ * * # . . . # | * * * * *
* * * . . . . . * * * * * * * . . . . * * * * * * . . ~ ~ ~ # # # # # . . . . * * *
 * * . * . . . . . . . . * * . . . . . . * * * * * * . . ~ ~ * * * * * . . . = = * *
  * . . . . . . . . * * . * * . * * * . . * * * # # # # . . ~ * * . . . . . = = = *
   * . . * . . * * * * . * * * . . * * * . * * # . . . . ~ ~ * = = . * . . . * * *
    * . * * . * * * * . . * * * . * * * * . . . . . . . ~ * * * = . . * * . * *
     * . . * . * * . . . . * * * . . * . * * # . . . ~ ~ . . * . . = * * * *
      * * . * . * * . . . . . * * . * . . * # . . . ~ ~ . . . . = = = * *
       * * . . . * * . . . . * * . * . . * # # | # ~ ~ . . . . = = = *
        * * . * . . * * . . . . . . * * . . . . * * ~ * . . . = * *
         * * * * . . , * * * * . . . * * * * * * ~ ~ * . . * * *
          * * * * , , , * * . . . . * * * ~ ~ ~ ~ * * . . * *
           A A , , , , , * * . . . * * ~ ~ * ~ * * . . * *
            A , A , , , , * * * . * ~ ~ * * * * . . . *
             , , , , , , , * A * * ~ ~ * . . . . . *
              A , , , , A * A , A * ~ * . . . = =
               , , , , , , , , A ~ ~ * _ . = =
                ~ ~ ~ , , , ~ ~ ~ ~ A * * =
                 ~ ~ ~ . ~ ~ ~ ~ A A A A
                  ~ A , ~ ~ , , , A A
                   A A , , , , , A
                    A , , , , ,
                     , , , ,
                      , ,
'''

[legend]
"#" = { t = "Wall", e = [] }
"*" = { t = "Rock", e = [] }
"," = { t = "Grass", e = [] }
"." = { t = "Ground", e = [] }
"=" = { t = "Magma", e = [] }
"A" = { t = "Tree", e = [] }
"_" = { t = "Gate", e = [] }
"|" = { t = "Door", e = [] }
"~" = { t = "Water", e = [] }
