map = '''
                                                           . .
                                                        . . . .
                                                     # . . . . .
                                                  * # . . . . . .
                                               * * # . . . . . . .
                                            * * * # . . . . . . . .
                                         * # # # # # # + + # # # # #
                                      * * * . . . . . . . . . . . . .
                                   * * * * . * * * . . * . . . . . . .
                                * * * * * # # # # * * * * * * . . * * *
                             * * * * * * * * * * * * * * * * . . . * * *
                          * * * * * * * * * * * * * * * * * * . . * * * *
                       * * * * * * * * * * * * * * * * * * * * * * * * * *
                    * * * * * * * * * * * * * * * * * * * * * * * * * * * *
                 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
              * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
           * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
        * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     * * * * * * * * * * * * * * * * * * * * * * ~ ~ ~ * * * * * * * * * * * * *
  * * . * . * * * * * * * * * * * * * * * * * * * * * ~ * * * * * * * * * * * * *
 * * . . . . . * * * * * * * * * * * * * * * * * * ~ ~ ~ * * * * * * * * * * * * *
* * . . . . . . * * * * * * * * * * * * * * * * * * * ~ ~ ~ * * * * * * * * * * * *
 * * . * . . . . . . . . * * * * * * * * * * * * * * * # ~ ~ * * * * * * * * * * * *
  * . . . . . . . . * * * * * * * * * * * * * * # # # # . . ~ * * * * * * * * * * *
   * . . * . . * * * * * * * * * * * * * * * * # . . . . ~ ~ * * * * * * * * * * *
    * . * * . * * * * * * * * * * * * * * * * # . . . . ~ * * * * * * * * * * *
     * . . * . * * * * * * * * * * * * * * * # . . . ~ ~ . . * * * * * * * *
      * * . * * * * * * * * * * * * * * * * # . . . ~ ~ . . . * * * * * *
       * * . . . * * * * * * * * * * * * * # # # # ~ ~ . . . . * * * *
        * * . * . . * * * * * * * * * * * * * * * * ~ * . . . * * *
         * * * * . . , * * * * * * * * * * * * * ~ ~ * . . * * *
          * * * * , , , * * * * * * * * * ~ ~ ~ ~ * * . . * *
           % % , , , , , * * * * * * * ~ ~ * ~ * * . . * *
            % , % , , , , * * * * * ~ ~ * * * * . . . *
             , , , , , , , * % * * ~ ~ * . . . . . *
              % , , , , % * % , % * ~ * . . . . *
               , , , , , , , , % ~ ~ * * . * *
                ~ ~ ~ , , , ~ ~ ~ ~ % * * *
                 ~ ~ ~ . ~ ~ ~ ~ % % % %
                  ~ % , ~ ~ , , , % %
                   % % , , , , , %
                    % , , , , ,
                     , , , ,
                      , ,
'''

[legend]
"~" = { t = "Water", e = [] }
"%" = { t = "Tree", e = [] }
"," = { t = "Grass", e = [] }
"*" = { t = "Rock", e = [] }
"+" = { t = "Door", e = [] }
"." = { t = "Ground", e = [] }
"#" = { t = "Wall", e = [] }
