[package]
name = "calx-ecs"
version = "0.0.1"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Serializable entity component system for games"
keywords = ["gamedev", "ecs"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = "0.7"
serde_macros = "0.7"

[dev-dependencies]
bincode = "0.5"
