[package]

name = "content"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "content"

[dependencies.rand]
[dependencies.num]
[dependencies.image]
[dependencies.rustc-serialize]

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
