[package]

name = "content"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "content"

[dependencies]
rand = "*"
num = "*"
image = "*"
serde = "*"
serde_macros = "*"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
