[package]
name = "calx-grid"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Grid map utilities for games"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.1"
rand = "0.3"
serde = "0.7"
serde_macros = "0.7"
euclid = "0.7"
