[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies.num]
[dependencies.uuid]
[dependencies.anymap]

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
