[package]

name = "world"
version = "0.1.0"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
num = "0.1"
rand = "0.3"
vec_map = "0.6"
serde = "0.8"
serde_derive = "0.8"
bincode = "0.6"
image = "0.10"
euclid = "0.10"
lazy_static = "0.2"

[dependencies.vitral]
git = "https://github.com/rsaarelm/vitral"

[dependencies.vitral-atlas]
git = "https://github.com/rsaarelm/vitral"

[dependencies.calx-ecs]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-alg]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-resource]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-grid]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-color]
git = "https://github.com/rsaarelm/calx"
