[package]

name = "world"
version = "0.1.0"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
num = "0.1"
rand = { version = "0.5", features = ["serde1"] }
vec_map = "0.8"
ron = "0.2"
euclid = "0.17"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
calx-ecs = "0.6"
calx = { git = "https://github.com/rsaarelm/calx" }
image = "0.19"
