[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
num = "*"
rand = "*"
vec_map = "*"
serde = "*"
serde_macros = "*"
bincode = "*"
cgmath = "0.7"

[dependencies.calx-ecs]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-alg]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-grid]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-color]
git = "https://github.com/rsaarelm/calx"
