[package]

name = "world"
version = "0.1.0"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
num = "0.1"
rand = "0.3"
vec_map = "0.7"
bincode = { git = "https://github.com/TyOverby/bincode" } # TODO: Waiting for serde 1.0 version to hit crates.
euclid = "0.11"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
calx-ecs = "0.6"
toml = "0.4"
error-chain = "0.10"
calx-alg = { git = "https://github.com/rsaarelm/calx" }
calx-grid = { git = "https://github.com/rsaarelm/calx" }
calx-color = { git = "https://github.com/rsaarelm/calx" }
