[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
num = "*"
rand = "*"
vec_map = "*"
serde = "*"
serde_macros = "*"
bincode = "*"

[dependencies.calx_ecs]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"

[dependencies.content]
path = "../content"
