[package]
name = "calx-layout"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "GUI layout utilities for games"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
cgmath = "0.8"
num = "0.1"
serde = "0.7"
serde_macros = "0.7"
