[package]
name = "calx-system"
version = "0.3.0-alpha"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Miscellaneous operating system related utilities"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
time = "0.1"
image = "0.13"
tempdir = "0.3"
