[package]
name = "calx_ecs"
version = "0.0.1"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Rust entity component library"
keywords = ["gamedev", "ecs"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = "*"
serde_macros = "*"

[dev-dependencies]
bincode = "*"
