[package]
name = "calx-color"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Color datatypes"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
image = "0.9"
num = "0.1"
serde = "0.7"
serde_macros = "0.7"
