[package]
name = "calx-color"
version = "0.3.0-alpha"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Color datatypes"
keywords = ["gamedev"]
license = "MIT OR Apache-2.0"

[dependencies]
image = "0.13"
num = "0.1"
serde = "1.0"
serde_derive = "1.0"
