[package]
name = "display"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]

[lib]
name = "display"

[dependencies]
time = "0.1"
euclid = "0.10"
image = "0.10"
glium = "0.15"
vitral = { git = "https://github.com/rsaarelm/vitral" }
vitral-atlas = { git = "https://github.com/rsaarelm/vitral" }
calx-resource = { git = "https://github.com/rsaarelm/calx" }
calx-grid = { git = "https://github.com/rsaarelm/calx" }
calx-color = { git = "https://github.com/rsaarelm/calx" }
calx-alg = { git = "https://github.com/rsaarelm/calx" }
world = { path = "../world" }
