[package]
name = "display"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]

[lib]
name = "display"

[dependencies]
euclid = "0.10"
image = "0.10"
glium = "0.15"

# TODO: Make Vitral into a proper crate eventually.
[dependencies.vitral]
git = "https://github.com/rsaarelm/vitral"

[dependencies.calx-resource]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-grid]
git = "https://github.com/rsaarelm/calx"

[dependencies.calx-color]
git = "https://github.com/rsaarelm/calx"

[dependencies.world]
path = "../world"
