[package]
name = "display"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]

[lib]
name = "display"

[dependencies]
time = "0.1"
euclid = "0.15"
image = "0.17"
glium = "0.18"
vec_map = "0.8"
calx-ecs = "0.6"
vitral = { git = "https://github.com/rsaarelm/vitral", features = ["glium_backend"] }
calx = { git = "https://github.com/rsaarelm/calx" }
world = { path = "../world" }
